### PR TITLE
Added support for binary files

### PR DESCRIPTION
**Pull request by mikko-tormala**
Currently copy-files-from-to will not work with binary (images,fonts,etc) files due to all files being read as utf8.

This PR will automatically detect binary files using `is-utf8`, and use the proper encoding to read the file.

### CODE REVIEW

**Comment by webextensions** [comment]
@mikko-tormala 
Thanks for the PR. It looks good.

I hadn't considered that use case.

Some more things to consider:
* Can we detect the content type automatically? Maybe something like https://www.npmjs.com/package/is-utf8 might help. As a user, I would like to avoid any extra configuration like `binaryExtensions`.
* This may lead to adding support for more encodings
* Auto-detection would help in case of remote resources as well

Note to self:
* Add tests
* Add comments in README.md about the parts which are generated

**Comment by mikko-tormala** [comment]
I updated the PR to automatically detect binary files using is-utf8
I removed the binaryExtensions setting, so no extra configurations needed now.

**Comment by mikko-tormala** [comment]
@webextensions Any objections to this updated automatic version?

**Comment by webextensions** [comment]
@mikko-tormala 
Hi ... I couldn't spend time for the review yet ... added you as a collaborator in this GitHub repo to make it easier for you to continue with changes or any further enhancements :-)

Assuming that your changes would be fine, you may merge them to master branch.

Once I have a quick review, I'll publish the changes to npm :-)

**Comment by mikko-tormala** [comment]
@webextensions I've been using the modified version now for a good while and feel it's solid. I'll merge the changes to master.

**Comment by webextensions** [comment]
@mikko-tormala 
Published copy-files-from-to@1.2.0 to npm :+1:

**Pull request merged**
